name: portfolio

services:
  # Development Service: docker compose --profile dev up --watch
  portfolio-dev:
    build:
      context: .
      target: dev
    image: portfolio-dev:1.0
    container_name: portfolio-dev
    ports:
      - 3001:3001
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - package.json
        - action: rebuild
          path: package.json
    profiles:
      - dev

  # Production Service: docker compose --profile prod build
  portfolio-prod:
    build:
      context: .
      target: prod  
    image: portfolio-prod:1.0
    container_name: portfolio-prod
    mem_limit: 1024m # good practice for production
    ports:
      - 3002:3002
    profiles:
      - prod